### ISSUE TITLE
您好，如何跟您一样显示更加灵活的侧边栏。

### ISSUE THREAD

**Issue by MuDemuder** [Wangjunyu/Talk-to-me#2]
目前，在Siderbar下显示4种方案，post等。

目前想法是在<about><分类>这些页面不显示侧边栏，而在具体文章打开进去后显示侧边栏。

是需要具体修改这些页面的代码吗？

**Comment by Wangjunyu** [comment]
@MuDemuder  你好，这个不需要修改代码，在主题的配置文件中就有相应的配置。
